export enum ClientHomeAction {
    NO_ACTION = "NO_ACTION",
    APPROVE_OR_REJECT = "APPROVE_OR_REJECT",
    VIEW_ORDER = "VIEW_ORDER",
    REDEEM_SERVICE = "REDEEM_SERVICE",
    PAY_SERVICE = "PAY_SERVICE"
}